config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :articles do
  	resources :comments
  	member do
  		put "like" => "articles#like"
  	end
  end
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_votable
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_attached_file :image, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # has_many :comments, dependent: :destroy
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action only: [:show, :edit, :update, :destroy, :like]
  respond_to :html, :js

	def index
    	@articles = Article.all
  end

	def show
    	@article = Article.find(params[:id])
  end

  def new
      @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

 	def create
  		@article = Article.new(article_params)

  		if @article.save
  		  redirect_to @article
      else
        render 'new'
      end
	end

  def update
      @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to articles_path
  end

  def like
    @article = Article.find(params[:id])
    @article.like_by current_user

    respond_to do |format|
      format.html { redirect_to @article }
      format.js 
    end
    
    redirect_to @article
  end

  private
  def article_params
  	params.require(:article).permit(:title, :text, :image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<div class="formContainer">

  <div class="back_button">
    <%= link_to 'Back', articles_path %>
  </div>

  <%= form_with model: @article, local: true, html: { multipart: true } do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="form">
    <%= form.label :body %><br>
    <%= form.text_area :text %>
  </div>

  <label class="fileContainer">
    IMAGE
    <%= form.file_field :image %>
  </label>

    <%= form.submit 'SUBMIT' %>

<% end %>

  <div class="back_button">
    <%= link_to 'Home', controller: '/welcome' %>
    <%= link_to 'News', controller: '/articles' %>
    <%= link_to 'Back', :back %>
  </div>

  <script>
    $('svg').css('fill', 'black');
    $('#toggle').remove();
    $('#menu').remove();
  </script>

</div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="art_index"> <!--Wraps the entire article index page into a div.-->

<!--   <% articles = [] %>  This block of ruby reverses the article order so the newest ones show up first on the index page.
  <% @articles.each do |x| %>
    <% articles.unshift(x) %>
  <% end %> -->


  <% @articles.reverse.each do |article| %>

  <div class="listing"> <!-- Wraps each article listing into its own div. This includes image, title, and body text. -->

    <span class="list_img"><%= image_tag article.image.url %></span> <!-- Wraps the image in its own seperate div so it's easier to manipulate. -->

    <div class="index_wrap"> <!-- Wraps the title and body into div so they move together when hovered over. -->
      <h2><%= link_to article.title, article_path(article) %>.</h2>
      <div class="art_ind_bar"></div> <!-- This is just the white bar. -->
      <div class="hide_para"> <!-- Wraps the body text into it's seperate div so it can be moved and hidden. -->
        <%= article.text[0..256] %>
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/articles/like.js.erb
$('.likes_art').on('ajax:success', function() {
  // $(this).closest('.likes_art').html('+LIKES[<%= escape_javascript @article.get_upvotes.size %>]');
  console.log('HEY!');
});

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div id="current_article"> <!-- Wraps entire article in a div. -->

	<div class="cur_img"> <!-- Wraps image in a div so it's easier to manipulate. -->
		<%= image_tag @article.image.url %>
	</div>

	<div class="article_container"> <!-- Wraps title, body text, and comments button into a div. -->
		<div class="current_bar"></div> <!-- White bar. -->

		<div class="article_title"> <!-- Wraps title into a div. -->
		   <h1><%= @article.title %>.</h1>
		</div>
		
		<div class="current_para">  <!-- Wraps body text into div. -->
			<%= simple_format @article.text %>
		</div>

		<h3 class="comms_open" style="cursor:pointer" onclick="openCom()">COMMENTS[<%= @article.comments.size %>]</h3> <!-- Comments button. Uses .js to function. -->

		<h3 class="comms_open edit" style="margin-right: 1em;"><%= link_to 'EDIT', edit_article_path(@article) %></h3>

		<!-- <h3 class="comms_open" style="margin-right: 1em;"><%= link_to 'X', article_path(@article), method: :delete %></h3> -->

		<h3 class="comms_open likes_art" style="margin-right: 1em;"><%= link_to '+LIKES', like_article_path(@article), remote: :true, method: :put %>[<%= @article.votes_for.size %>]</h3>

	</div>

	<div id="thisComments" class="comments_section"> <!-- Wraps comment section into its own div. -->

		<span class="signin">
			<% if user_signed_in? %> <!-- User Sign In -->
	          <%= link_to destroy_user_session_path, method: :delete do %>
	            <span>Log Out</span>
	          <% end %>
	        <% else %>
	          <%= link_to new_user_session_path do %>
	          	<span>Log In</span>
	          <% end %>
	        <% end %>
    	</span>

		<a href="javascript:void(0)" class="closebtn" onclick="closeCom()">&times;</a> <!-- 'x' closes comments window. uses js.-->
		
		<div class="comm_display"> <!-- wraps comments form into a div. -->
			<%= render @article.comments %>
			<%= render 'comments/form' %>
		</div>

	</div>

</div>

<!-- Javascript functions -->
<script>
function openCom() {
    document.getElementById("thisComments").style.width = "30%";
    document.getElementById("current_article").style.marginRight = "30%";
}

function closeCom() {
    document.getElementById("thisComments").style.width = "0";
    document.getElementById("current_article").style.marginRight = "0";
}
</script>

app/views/comments/_comment.html.erb
<div class="comm_bar"></div>
<h3>
  <%= comment.commenter %>.
</h3>
 
<p class="comm_body">
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ]) do |form| %>

    <h3>NAME</h3>
    <%= form.text_area :commenter %> <br />
    
    <h3>COMMENT</h3>
    <%= form.text_area :body %> <br />

    <%= form.submit 'SUBMIT' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Un:Marked</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>   

    <nav>

      <!-- SVG is the logo. It draws it out based on the coordinates above instead of using an actual image. Magic! -->
      <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="15vh" height="13vh" viewBox="0 0 564.706 457.315" enable-background="new 0 0 564.706 457.315" xml:space="preserve">
      <polygon points="474.52,75.913 390.628,242.57 308.252,78.937 308.309,272.824 361.262,366.238 419.99,366.238 472.947,272.824 
        472.947,457.315 564.706,457.315 564.706,75.913 "/>
      <rect x="0.013" width="564.693" height="57.803"/>
      <path d="M132.676,373.628c-24.764-4.068-39.731-23.412-39.731-54.416V75.913H0V321.34c0,79.249,58.789,131.26,132.676,135.654
        V373.628z"/>
      <path d="M193.861,75.913v243.299c0,30.582-15.362,49.844-39.735,54.265v83.448c73.483-4.82,132.676-56.709,132.676-135.585V75.913
        H193.861z"/>
      </svg>
      <!-- SVG [END] -->

      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <ul>
          <li><h3><%= link_to 'HOME', controller: '/welcome' %></h3></li>
          <li><h3><%= link_to 'NEWS', controller: '/articles' %></h3></li>
          <li onclick="loadStand()" class="clicker"><h3>STANDINGS</h3></li>
          <li onclick="loadStat()" class="clicker2"><h3>STATS</h3></li>
        </ul>
      </div>

      <span class="hamburger" onclick="openNav()">&#9776;</span>

    </nav>

    <!--STANDINGS BEGIN-->
    <div class="stand">
        <button class="close" aria-label="Close">✕</button>
        <table id="stand"></table>
    </div>
    <!--STANDINGS END-->

    <!--STATS BEGIN-->
    <div class="stat">
      <button class="close2" aria-label="Close">✕</button>
      <table id="stat"></table>
    </div>
    <!--STATS END-->

    <%= yield %>
  </body>

  <script>

    function openNav() {
      document.getElementById("mySidenav").style.width = "20vw";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

    $('.clicker').on('click', function() {
      $('.stand').css({"opacity": "1", "z-index": "10", "transform": "scale(1)"});
    });

    $('button.close').on('click', function() {
      $('.stand').css("transform", "scale(0.5)");
      $('.stand').css("opacity", "1");
      $('.stand').css("z-index", "-5");
    });

    $('.clicker2').on('click', function() {
      $('.stat').css({"opacity": "1", "z-index": "15", "transform": "scale(1)"});
    });

    $('button.close2').on('click', function() {
      $('.stat').css("transform", "scale(0.5)");
      $('.stat').css("opacity", "0");
      $('.stat').css("z-index", "-5");
    });
  </script>

</html>

app/views/welcome/index.html.erb
<!-- Ruby [START] -->
<% database = @articles.reverse %>

<% z = database.first(4) %>

<% first = z.first(1) %>

<% z.shift %>

<% rating = [] %>

<% feerst =  z.first %>

<% z.shift %>

<% rating << feerst %>

<% two = z.first %>

<% third = z.last %>

<% if two.votes_for.size > feerst.votes_for.size %>
	<% rating.unshift(two) %>
<% else %>
	<% rating << two %>
<% end %>

<% if third.votes_for.size > feerst.votes_for.size && third.votes_for.size > two.votes_for.size %>
	<% rating.unshift(third) %>
<% elsif third.votes_for.size > two.votes_for.size && two == rating.last || third.votes_for.size > feerst.votes_for.size && feerst == rating.last %>
	<% rating.insert(1, third) %>
<% else %>
	<% rating << third %>
<% end %>
<!-- Ruby [END] -->

<div class="container">

	<main>
		<div class="main_wrapper">
			<% first.each do |y| %>
				<div class="main_image">
					<%= image_tag y.image.url %>
					<div class="main_title">
						<h1><%= link_to y.title, article_path(y) %>.</h1>
						<div class="main_bar"></div>
						<div class="main_par"><%= simple_format y.text %></div>
					</div>
				</div>
			<% end %>
		</div>
	</main>

	<!--//////////////-->

	<div class="sidebar">
	<% rating.each do |a| %>
		<div class="arti1">
			<span class="side_img"><%= image_tag a.image.url %></span>
			<div class="mini_wrap">
				<h3><%= link_to a.title, article_path(a) %>.</h3>
				<div class="mini_bar"></div>
				<p><%= a.text[0..180] %></p>
			</div>
		</div>
	<% end %>

	</div>

</div>